# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def swiftPods
  pod 'Alamofire'
  pod 'XCoordinator'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxCoreData'
  pod 'Kingfisher'
end

target 'NewsApp' do
  use_frameworks!
  swiftPods
end
